; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html
[env:giga_r1_m7]
platform = ststm32
board = giga_r1_m7
framework = arduino
monitor_speed = 115200
upload_protocol = dfu
lib_deps =
  https://github.com/SolidGeek/VescUart.git#development
  coryjfowler/mcp_can
  https://github.com/pierremolinaro/acanfd-giga-r1.git
  
monitor_echo = yes
monitor_filters = send_on_enter
monitor_eol = LF